allowBuilds:
  "@parcel/watcher": set this to true or false
  "@prisma/engines": set this to true or false
  "@swc/core": set this to true or false
  better-sqlite3: set this to true or false
  bufferutil: set this to true or false
  canvas: set this to true or false
  edgedriver: set this to true or false
  esbuild: set this to true or false
  geckodriver: set this to true or false
  libpq: set this to true or false
  msw: set this to true or false
  prisma: set this to true or false
  sqlite3: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAge: 0
