name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: bjmhe/workflows/.github/workflows/release-vp.yml@feat/release-vp
    with:
      publish: true
    permissions:
      contents: write
      id-token: write
